### ISSUE TITLE
add inv command: deploy-local

### ISSUE THREAD

**Issue by pogobanane** [TUM-DSE/doctor-cluster-config#121]
for users that want to redeploy nixos on, say, graham, but dont have ssh root login nor sops admin keys nor nix installed on their laptop. 

1. ssh to graham
2. clone doctor-cluster-config
3. inv deploy-local
4. inv does: cp ./ /etc/nixos && sudo nixos-rebuild switch

**Comment by Mic92** [comment]
Copying is not even required:

```
sudo nixos-rebuild swich --flake .#
```

is enough.

**Comment by Mic92** [comment]
Fixed in https://github.com/TUM-DSE/doctor-cluster-config/commit/48616502ccef923a0a7184044c8d83ad53441e50
