### ISSUE TITLE
fix backups

### ISSUE THREAD

**Issue by pogobanane** [TUM-DSE/doctor-cluster-config#125]
zroot1 @ bill is full. The backup tasks `journalctl -u znapzend` @ nardole is failing. The last backup is from 12.5. 

Follow up work:

- monitoring for zpool state
- #94 dont send success to prometheus when backup fails
- make eva backups available to staff

**Comment by Mic92** [comment]
I fixed znapzend today. But I will probably switch to `syncoid`, which seems saner.
