### ISSUE TITLE
ssh: christina doesnt trust rose.dos.cit.tum.de

### ISSUE THREAD

**Issue by pogobanane** [TUM-DSE/doctor-cluster-config#324]
it only trusts rose.dse.in.tum.de

**Comment by pogobanane** [comment]
maybe none of the ssh certs are signed for the new domains yet?

**Comment by Mic92** [comment]
Yes. I mentioned that here: https://github.com/TUM-DSE/doctor-cluster-config/pull/369#issuecomment-1736866121

**Comment by Mic92** [comment]
You also need to update the sshd configuration to include the new domain.

**Comment by Mic92** [comment]
fixed.
