### ISSUE TITLE
delete cache during installation

### ISSUE THREAD

**Issue by pogobanane** [TUM-DSE/doctor-cluster-config#70]
repeated inv install-nixos fails because /root/.cache/nix has to be deleted first

**Comment by SuperSandro2000** [comment]
Thats very strange, `~/.cache/nix` shouldn't be needed to be deleted at all.

**Comment by Mic92** [comment]
we are currently installing nixos using a flake url: https://github.com/TUM-DSE/doctor-cluster-config/blob/master/tasks.py#L227
but instead we should just upload the current configuration via rsync to be able to make modification without cache busting.

**Comment by pogobanane** [comment]
obsolete, since we overhauled all install scripts
