### ISSUE TITLE
Deploying hosts from ubuntu laptops

### ISSUE THREAD

**Issue by pogobanane** [TUM-DSE/doctor-cluster-config#91]
nix shell .#nixboot-pixie-core can not execute netboot-pixie-core as root because the root shell will loose the nix path of the `nix shell`.

**Comment by Mic92** [comment]
To enable flakes follow: https://nixos.wiki/wiki/Flakes#Non-NixOS

**Comment by pogobanane** [comment]
> To enable flakes follow: https://nixos.wiki/wiki/Flakes#Non-NixOS

good point. 

> sudo -E should work

tried it - didnt work

> Otherwise just put sudo into pixiecore core script

oof. Its a solution though i guess

**Comment by Mic92** [comment]
https://github.com/TUM-DSE/doctor-cluster-config/commit/b45d7ef4f504612584a1501d1fa47785f9e8654d https://github.com/TUM-DSE/doctor-cluster-config/commit/e81de276c5d2dced5ec5e20036f5e0f45ebf1340
